spring:
  application:
    name: eureka-sv
  server:
    port: 8761
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  eureka:
    client:
      register-with-eureka: false
      fetch-registry: false
    instance:
      lease-renewal-interval-in-seconds: 0